#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

for f in "$ROOT"/scripts/*.sh; do
  bash -n "$f"
done

grep -q '^COCOOS_COMMIT=[0-9a-f]\{40\}$' "$ROOT/SOURCES.lock"
grep -q '^MOONLIGHT_COMMIT=[0-9a-f]\{40\}$' "$ROOT/SOURCES.lock"
grep -q '^AUDIO_COMMIT=[0-9a-f]\{40\}$' "$ROOT/SOURCES.lock"
grep -q 'part /boot/efi --fstype=efi' "$ROOT/config/moonlight-os.ks"
grep -q 'part / --fstype=xfs --size=11000 --grow' "$ROOT/config/moonlight-os.ks"
grep -q 'libva-intel-driver' "$ROOT/config/moonlight-os.ks"
grep -q '^libva-intel-media-drivergrep -q 'wifi.powersave=2' "$ROOT/config/moonlight-os.ks"
grep -q 'roamoff=1' "$ROOT/config/moonlight-os.ks"
grep -q 'MacBookPro14,1' "$ROOT/config/moonlight-os.ks"
grep -q 'hid_playstation' "$ROOT/config/moonlight-os.ks"
grep -q '^joystick-support$' "$ROOT/config/moonlight-os.ks"
grep -q '^evtest$' "$ROOT/config/moonlight-os.ks"
grep -q 'moonlight-red-terminal' "$ROOT/config/moonlight-os.ks"
grep -q '52-disable-dualsense-audio.conf' "$ROOT/config/moonlight-os.ks"
grep -q 'override.bluez5.roles = \[ a2dp_sink \]' "$ROOT/config/moonlight-os.ks"
grep -q 'override.bluez5.codecs = \[ sbc sbc_xq aac \]' "$ROOT/config/moonlight-os.ks"
grep -q 'override.bluez5.auto-connect = \[ a2dp_sink \]' "$ROOT/config/moonlight-os.ks"
grep -q 'bluetooth.profile-preference = "latency"' "$ROOT/config/moonlight-os.ks"
grep -q 'bluetooth.autoswitch-to-headset-profile = false' "$ROOT/config/moonlight-os.ks"
grep -q 'device.vendor.id = 1356' "$ROOT/config/moonlight-os.ks"
grep -q 'device.product.id = 3302' "$ROOT/config/moonlight-os.ks"

echo "Static validation passed."
 "$ROOT/config/moonlight-os.ks"
! grep -q '^intel-media-drivergrep -q 'wifi.powersave=2' "$ROOT/config/moonlight-os.ks"
grep -q 'roamoff=1' "$ROOT/config/moonlight-os.ks"
grep -q 'MacBookPro14,1' "$ROOT/config/moonlight-os.ks"
grep -q 'hid_playstation' "$ROOT/config/moonlight-os.ks"
grep -q '^joystick-support$' "$ROOT/config/moonlight-os.ks"
grep -q '^evtest$' "$ROOT/config/moonlight-os.ks"
grep -q 'moonlight-red-terminal' "$ROOT/config/moonlight-os.ks"
grep -q '52-disable-dualsense-audio.conf' "$ROOT/config/moonlight-os.ks"
grep -q 'device.vendor.id = 1356' "$ROOT/config/moonlight-os.ks"
grep -q 'device.product.id = 3302' "$ROOT/config/moonlight-os.ks"

echo "Static validation passed."
 "$ROOT/config/moonlight-os.ks"
grep -q 'wifi.powersave=2' "$ROOT/config/moonlight-os.ks"
grep -q 'roamoff=1' "$ROOT/config/moonlight-os.ks"
grep -q 'MacBookPro14,1' "$ROOT/config/moonlight-os.ks"
grep -q 'hid_playstation' "$ROOT/config/moonlight-os.ks"
grep -q '^joystick-support$' "$ROOT/config/moonlight-os.ks"
grep -q '^evtest$' "$ROOT/config/moonlight-os.ks"
grep -q 'moonlight-red-terminal' "$ROOT/config/moonlight-os.ks"
grep -q '52-disable-dualsense-audio.conf' "$ROOT/config/moonlight-os.ks"
grep -q 'device.vendor.id = 1356' "$ROOT/config/moonlight-os.ks"
grep -q 'device.product.id = 3302' "$ROOT/config/moonlight-os.ks"

echo "Static validation passed."
